# Generated by Django 4.2.5 on 2023-10-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'CEO'), (2, 'Head of Sales'), (3, 'Salesperson')], default=1, null=True),
        ),
    ]
