# Generated by Django 4.2.5 on 2023-10-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[('CEO', 'CEO'), ('Head of sales', 'Head of Sales'), ('Salesperson', 'Salesperson')], default='Salesperson', null=True),
        ),
    ]
