# Generated by Django 4.2.5 on 2023-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('HOS', 'Head of Sales'), ('Salesperson', 'Salesperson')], default='Salesperson', max_length=265, null=True),
        ),
    ]
