# Generated by Django 4.2.5 on 2023-10-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_userprofile_role1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role1',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('HOS', 'Head of Sales'), ('Salesperson', 'Salesperson')], default='Salesperson', max_length=265, null=True),
        ),
    ]
