# Generated by Django 4.2.5 on 2023-10-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_remove_userprofile_role1_alter_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='role',
            new_name='role_type',
        ),
    ]
