# Generated by Django 4.2.5 on 2023-10-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_alter_userprofile_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role_type',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('HOS', 'Head of Sales'), ('Salesperson', 'Salesperson')], default='Salesperson', max_length=265),
        ),
    ]
