# Generated by Django 4.2.5 on 2023-10-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_alter_userprofile_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
