# Generated by Django 4.2.5 on 2023-10-09 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticate', '0012_userprofile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='head_of_sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
